const ZHTW = {
    "Common work": "普通工作",
    "Military": "軍事",
    "The Arcane Association": "奧術協會",
    "Fundamentals": "基礎",
    "Combat": "戰鬥",
    "Magic": "魔法",
    "Dark magic": "黑魔法",
    "Properties": "資產",
    "Misc": "雜物",

    "Beggar": "乞丐",
    "Farmer": "農夫",
    "Fisherman": "漁夫",
    "Miner": "礦工",
    "Blacksmith": "鐵匠",
    "Merchant": "商人",
    "Squire": "侍從",
    "Footman": "步兵",
    "Veteran footman": "資深步兵",
    "Knight": "騎士",
    "Veteran knight": "資深騎士",
    "Elite knight": "菁英騎士",
    "Holy knight": "神聖騎士",
    "Legendary knight": "傳奇騎士",
    "Student": "學生",
    "Apprentice mage": "見習法師",
    "Mage": "法師",
    "Wizard": "巫師",
    "Master wizard": "大法師",
    "Chairman": "主席",

    "Concentration": "專注",
    "Productivity": "產能",
    "Bargaining": "議價",
    "Meditation": "冥想",
    "Strength": "力量",
    "Battle tactics": "戰術",
    "Muscle memory": "肌肉記憶",
    "Mana control": "魔力控制",
    "Immortality": "不朽",
    "Time warping": "時間扭曲",
    "Super immortality": "超級不朽",
    "Dark influence": "黑暗影響",
    "Evil control": "邪惡控制",
    "Intimidation": "威嚇",
    "Demon training": "惡魔訓練",
    "Blood meditation": "血之冥思",
    "Demon's wealth": "惡魔財富",

    "Skill xp": "技能經驗",
    "Job xp": "職業經驗",
    "Expenses": "花費",
    "Happiness": "幸福度",
    "Military pay": "軍事收入",
    "Military xp": "軍事經驗",
    "Strength xp": "力量經驗",
    "T.A.A. xp": "T.A.A.經驗",
    "Longer lifespan": "更長的壽命",
    "Gamespeed": "遊戲速度",
    "All xp": "所有經驗",
    "Evil gain": "邪惡增長",
    "Job pay": "職業收入",
    "Magic xp": "魔法經驗",

    "Homeless":"無家可歸",
    "Tent": "破帳篷",
    "Wooden hut": "破爛木屋",
    "Cottage": "小屋",
    "House": "房子",
    "Large house": "大房子",
    "Small palace": "小宮殿",
    "Grand palace": "大宮殿",

    "Book": "書籍",
    "Dumbbells": "啞鈴",
    "Personal squire": "私人侍從",
    "Steel longsword": "精鋼長劍",
    "Butler": "管家",
    "Sapphire charm": "藍寶石護符",
    "Study desk": "學習桌",
    "Library": "圖書館",

    "BeggarTip": "為了幾個銅板日夜掙扎。感覺每天都在死亡的邊緣。",
    "FarmerTip": "耕田種地。雖然不多，但這是一份誠實的工作。",
    "FishermanTip": "捕獲各種魚類，然後賣掉換取少量硬幣。這是一份輕鬆但收入微薄的工作。",
    "MinerTip": "深入危險的洞穴挖掘有價值的礦石。與所冒的風險相比報酬相當微薄。",
    "BlacksmithTip": "冶鍊礦石，為軍隊精心打造武器。這是一份受人尊敬、收入尚可的平民工作。",
    "MerchantTip": "穿梭於城鎮之間，以物易物。這份工作報酬不錯，而且不需要太多的手工勞動。",

    "SquireTip": "在戰場上背負你騎士的盾牌和劍。報酬微薄，但工作經驗相當寶貴。",
    "FootmanTip": "捨命與敵軍作戰。這是一份勇敢、值得尊敬的工作，但在大局中，你仍然一文不值。",
    "Veteran footmanTip": "比一般步兵更有經驗且更有用，能在戰場上殲滅敵軍。收入還不錯。",
    "KnightTip": "從頭到腳都覆蓋著鋼鐵，輕鬆地砍殺和刺穿敵軍士兵。這是一份收入可觀、受人尊敬的工作。",
    "Veteran knightTip": "利用你無與倫比的戰鬥力，毫不費力地屠殺敵人。軍隊中的大多數步兵都無法獲得如此高薪的工作。",
    "Elite knightTip": "配備最精良的裝備，以非凡的能力一舉殲滅敵軍中隊。這樣一支在戰場上令人生畏的部隊會得到極高的報酬。",
    "Holy knightTip": "用你充滿魔力的利刃在幾秒鐘內擊潰整支軍隊。極少數達到這一境界的菁英騎士會得到大量金幣。",
    "Legendary KnightTip": "舉世聞名，眨眼間毀滅整個國家。大約每隔一個世紀，只有一位聖騎士才有資格獲得如此尊崇的稱號。",

    "StudentTip": "學習魔力的理論並練習基本咒語。有少量津貼維持生計, 是成為法師必經的階段。",
    "Apprentice mageTip": "在法師監督下施展基本攻擊咒語。會提供可觀津貼維持生計。",
    "MageTip": "通過施放中級法術改變戰局，並指導其他見習法師。這份工作的薪資極為豐厚。",
    "WizardTip": "使用高級法術摧毀整個敵軍。只有極少數的法師有資格擔任這個角色，並且以極高的薪水作為獎勵。",
    "Master wizardTip": "擁有無與倫比的天賦，能肆意施展難以置信的魔法壯舉。據說大法師的破壞力足以將一個帝國從地圖上抹去。",
    "ChairmanTip": "管理奧術協會日常事務並研究真正的永生之道。主席每日收入天文數字般的薪水。",

    "ConcentrationTip": "通過練習高度專注來提高學習速度。",
    "ProductivityTip": "學會減少工作拖延，每天獲得更多工作經驗。",
    "BargainingTip": "學習貿易技巧和說服技能，降低各種開支。",
    "MeditationTip": "從內心獲得更大的幸福感。從內心獲得更大的幸福感。",

    "StrengthTip": "通過嚴酷的訓練來鍛煉身體和力量。在軍隊中，強壯的人收入更高。",
    "Battle tacticsTip": "制定和修改戰略，提高在軍事中獲得的經驗。",
    "Muscle memoryTip": "通過習慣和重複強化神經元，提高全身的力量增長。",

    "Mana controlTip": "增強全身魔力通道,成為更強大的魔法使用者。",
    "ImmortalityTip": "通過魔法手段延長你的壽命。然而，這真的是你一直努力追求的永生嗎……？",
    "Time warpingTip": "通過禁忌的技術扭曲時空，加快遊戲速度。",
    "Super immortalityTip": "利用古老禁忌的技術，令你的壽命遠遠超乎你的想像。",

    "Dark influenceTip": "利用邪惡賦予你的強大力量,使你輕易學會並掌握任何工作和技能。",
    "Evil controlTip": "馴服你內心洶湧澎湃、不斷增長的邪惡，提高轉世間的邪惡獲得。",
    "IntimidationTip": "學會散發魔鬼般的氣場，讓其他商人感到極度恐懼，迫使他們給你高額折扣。",
    "Demon trainingTip": "人類的軀體太過孱弱，無法抵禦惡魔的侵襲。利用禁忌方法慢慢化身為惡魔，迅速吸收知識。",
    "Blood meditationTip": "通過犧牲其他生靈來壯大和培養體內的邪惡，大幅增加邪惡的收益。",
    "Demon's wealthTip": "通過黑暗魔法的手段，使你從工作中獲得的硬幣數量倍增。",

    "HomelessTip": "睡在又髒又不舒服的街道上，每天晚上幾乎都要凍死。沒有比這更糟糕的了。",
    "TentTip": "用幾根軟弱無力的木棍撐起一張薄薄的破布。可怕的生活條件，但至少你有個棲身之所。",
    "Wooden hutTip": "破爛的木頭和髒兮兮的乾草用馬糞粘在一起。比帳篷結實多了，不過臭味也不好聞。",
    "CottageTip": "木架結構，茅草屋頂。以合理的價格提供體面的居住條件。",
    "HouseTip": "用石磚和堅固木材建成的建築，內有幾個房間。雖然價格昂貴，但居住舒適。",
    "Large houseTip": "比普通房子大得多，擁有更多的房間和多個樓層。建築相當寬敞，但價格不菲。",
    "Small palaceTip": "一座非常富麗堂皇、精心建造的建築，以銀等貴金屬鑲邊。維持奢華生活的費用極高。",
    "Grand palaceTip": "完全由金銀打造的宏偉府邸。提供極盡奢華和舒適的生活條件，價格高得令人髮指。",

    "BookTip": "記下你的所有思想和發現，讓你學習速度大大提高。",
    "DumbbellsTip": "在劇烈運動中使用的重型工具，可以讓你比以前更快地增強和積累力量。",
    "Personal squireTip": "協助日常事務，讓你有更多時間專注工作。",
    "Steel longswordTip": "殺敵的良劍，讓你在戰鬥中更快獲得經驗。",
    "ButlerTip": "隨時保持家中清潔，每天準備三餐美食，讓你心情愉悅沒有壓力。",
    "Sapphire charmTip": "嵌有稀有藍寶石，激活身體更多魔力通道，學習魔法事半功倍。",
    "Study deskTip": "提供專業文具和設備的專用空間，助你學術研究更上一層樓。",
    "LibraryTip": "收藏了大量書籍，每本書籍都包含從基本生活技能到複雜魔法咒語的大量信息。",

    "p": "鉑",
    "g": "金",
    "s": "銀",
    "c": "銅",

    "Play": "繼續",
    "Pause": "暫停",
    "Income/day": "收入/日",
    "Effect": "效果",
    " evil": " 邪惡",
    "Disable warp": "停止時間扭曲",
    "Enable warp": "使用時間扭曲"
}